version: '3'

dotenv: ['custom.env', 'default.env']

tasks:
  default:
    desc: List available tasks
    cmds:
      - task -l

  install:
    desc: Install dependencies with bun
    cmds:
      - |
        bun install

  build:
    desc: Build the library
    cmds:
      - |
        bun run build

  format:
    desc: Format the code with bun
    cmds:
      - |
        bun format

  serve:
    desc: Run a bun development server
    interactive: true
    cmds:
      - |
        bun dev

  test:
    desc: Run the tests, currently only unit tests
    interactive: true
    cmds:
      - |
        bun test:unit

  prerelease:
    desc: 'Prerelease'
    summary: Bump version with alpha preid and publish to custom registry
    cmd: |
      echo "Using registry: {{.NPM_REGISTRY}}"
      npm version prerelease --preid=alpha
      bun run build
      npm publish --registry "{{.NPM_REGISTRY}}"
    sources:
      - package.json
      - custom.env
    generates:
      - package.json
