name: Build Vue
on:
  push:
    branches: [ next ]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v4
    - uses: actions/checkout@v4
      with:
        ref: master
        sparse-checkout: docs
        sparse-checkout-cone-mode: false
    - name: Set Node.js 21.x
      uses: actions/setup-node@v3
      with:
        node-version: 21.x
    - run: corepack enable

    - name: Run install
      uses: borales/actions-yarn@v4
      with:
        cmd: install # will run `yarn install` command
    - name: Build production bundle
      uses: borales/actions-yarn@v4
      with:
        cmd: build # will run `yarn build` command
    - run: mv dist docs/pad
    - name: Deploy 🚀
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        publish_branch: gh-pages
