name: Build Vue
on:
  push:
    branches: [ next ]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v3

    - name: Set Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - run: corepack enable

    - name: Run install
      uses: borales/actions-yarn@v4
      with:
        cmd: install # will run `yarn install` command
    - name: Build production bundle
      uses: borales/actions-yarn@v4
      with:
        cmd: build # will run `yarn build` command
 
