name: Build Vue
on:
  push:
    branches: [ next ]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v4
    - uses: actions/checkout@v4
      with:
        ref: master
        sparse-checkout: docs
        sparse-checkout-cone-mode: false
        path: master
    - uses: oven-sh/setup-bun@v2
    - run: bun install
    - run: bun run vite build --base /OntoPad/pad/
    - run: mv dist master/docs/pad
    - name: Build page
      uses: actions/jekyll-build-pages@v1
      with:
        source: master/docs
        destination: _site
    - run: find _site
    - name: Deploy 🚀
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _site
        publish_branch: gh-pages
